# Generated by Django 5.0.2 on 2024-02-16 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('register_time', models.DateTimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_full_name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('user_age', models.IntegerField()),
                ('position_name', models.TextField(choices=[('praktikant', 'praktikant'), ('professional_ishchi', 'professional_ishchi'), ('mike', 'mike'), ('micheal', 'micheal'), ('bexrux', 'bexrux'), ('javohir', 'javohir'), ('ozod', 'ozod')])),
            ],
        ),
        migrations.CreateModel(
            name='EndService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tovar_nomi', models.TextField()),
                ('sklad_tovar', models.TextField(null=True)),
                ('usta', models.CharField(choices=[('praktikant', 'praktikant'), ('professional_ishchi', 'professional_ishchi'), ('mike', 'mike'), ('micheal', 'micheal'), ('bexrux', 'bexrux'), ('javohir', 'javohir'), ('ozod', 'ozod')], max_length=255)),
                ('service_price', models.IntegerField()),
                ('enddate', models.DateTimeField()),
                ('comments', models.TextField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceXizmati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandice_name', models.TextField()),
                ('merchandice_amount', models.IntegerField()),
                ('technique_color', models.CharField(max_length=255)),
                ('status', models.TextField()),
                ('date', models.DateTimeField()),
                ('tuzatish_vaqti', models.DateTimeField()),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicename')),
            ],
        ),
        migrations.CreateModel(
            name='ReturnService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='receptionist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
        migrations.CreateModel(
            name='BazaItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField()),
                ('cash_sum', models.CharField(choices=[('dollar', 'dollar'), ('sum', 'sum'), ('click', 'click'), ('nasiya', 'nasiya')], max_length=255)),
                ('price', models.IntegerField()),
                ('brend', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('kirim_summa', models.IntegerField()),
                ('chiqim_summa', models.IntegerField()),
                ('seriya_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
